version: '3'
services:
  ### PHP-FPM Container
  php-fpm:
    platform: linux/x86_64
    build: ./build/php-fpm
    container_name: vvly-backend-php
    hostname: backend-php
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    restart: always
  
  ### NGINX Container
  nginx:
    platform: linux/x86_64
    build: ./build/nginx
    container_name: vvly-backend-nginx
    hostname: backend-nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./:/var/www
    ports:
      - "8000:8000"
    links:
      - php-fpm
    restart: always
  db:
    platform: linux/x86_64
    container_name: vvly-backend-db
    hostname: db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: analytic
      MYSQL_USER: analytic
      MYSQL_PASSWORD: TRBIeBLakoh2TSn4
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - "./build/init_test_db.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
volumes:
  db-data: